const archiveInfo = [
  {
    id: "recharge",
    imgUrl: "/static/recharge/index.jpg",
    tags: ["Backend"],
    firstImage: "/static/recharge/documentation/3.jpg",
    grid: [
      "/static/recharge/documentation/4.jpg",
      "/static/recharge/documentation/tnet.jpeg",
    ],
    lastImage: "/static/recharge/documentation/t.jpeg",
    secondImage: "/static/recharge/documentation/1.jpg",
    thirdImage: "/static/recharge/documentation/main.jpg",
    finalImage: null,
    team: "Studio Elsewhere",
    role: ["Creative Technologist", "Software Engineer"],
    photoCount: 6,
    year: 2022,
    title: "Recharge Rooms",
    link: "https://www.redefiningcountry.com",
    blurb:
      "Immersive biophilic private spaces to support the well-being and recovery of care providers. ",
    concept:
      "Studio Elsewhere’s Recharge Rooms are immersive biophilic private spaces that include music, scent, lighting, and sound, designed with research support from the Abilities Research Center at the Icahn School of Medicine at Mount Sinai to support the well-being and recovery of care providers. ",
    process:
      "Studio Elsewhere’s Recharge Rooms are immersive biophilic private spaces that include music, scent, lighting, and sound, designed with research support from the Abilities Research Center at the Icahn School of Medicine at Mount Sinai to support the well-being and recovery of care providers. ",
    description:
      "Studio Elsewhere’s Recharge Rooms are immersive biophilic private spaces that include music, scent, lighting, and sound, designed with research support from the Abilities Research Center at the Icahn School of Medicine at Mount Sinai to support the well-being and recovery of care providers. ",
    additional: null,
  },
  {
    id: "flourish",
    imgUrl: "/static/flourish/wave.jpg",
    tags: ["Backend", "UI/UX"],
    firstImage: "/static/flourish/energy.jpeg",
    grid: [
      "/static/flourish/color.jpeg",
      "/static/flourish/r.jpeg",
      "/static/flourish/wave.jpg",
      "/static/flourish/room.jpeg",
    ],
    lastImage: null,
    secondImage: null,
    thirdImage: null,
    finalImage: null,
    team: "Studio Elsewhere",
    role: ["Creative Technologist", "Software Engineer"],
    photoCount: null,
    year: 2022,
    title: "Flourish",
    link: "https://www.redefiningcountry.com",
    blurb: "Learn more about the history of the key sounds of the South.",
    concept: null,
    process: null,
    description:
      "The key idea of this project is to highlight BIPOC stories of the South and rewrite the narrative that country music is a white art form. This project includes 3D modeled flowers that are significant to the cultural groups being represented and music snippets gathered from the Spotify API to provide a brief overview of the modern and past sounds of country music.",
    additional: null,
  },
  {
    id: "country",
    imgUrl: "/static/country/bg1.jpg",
    tags: ["Frontend", "UI/UX"],
    year: 2022,
    firstImage: "/static/country/bg1.jpg",
    grid: null,
    lastImage: "/static/country/bg0.jpeg",
    secondImage: "/static/country/documentation/1.jpg",
    thirdImage: "/static/country/documentation/main.jpg",
    finalImage: "/static/country/bg11.jpeg",
    team: "Studio Elsewhere",
    role: ["Creative Technologist", "Software Engineer"],
    photoCount: null,
    title: "Redefining Country Roads",
    link: "https://www.redefiningcountry.com",
    blurb: "Learn more about the history of the key sounds of the South.",
    concept: null,
    process: null,
    description:
      "The key idea of this project is to highlight BIPOC stories of the South and rewrite the narrative that country music is a white art form. This project includes 3D modeled flowers that are significant to the cultural groups being represented and music snippets gathered from the Spotify API to provide a brief overview of the modern and past sounds of country music.",
    additional: null,
  },
  {
    id: "beats",
    imgUrl: "/static/beats/beats.jpg",
    tags: ["Unity", "UI/UX"],
    year: 2021,
    firstImage: "/static/beats/beats.jpg",
    grid: null,
    lastImage: null,
    secondImage: null,
    thirdImage: null,
    finalImage: "/static/beats/image3.png",
    team: "Studio Elsewhere",
    role: ["Creative Technologist", "Software Engineer"],
    photoCount: null,
    title: "Distant Beats",
    link: null,
    blurb:
      "A virtual world that visualizes the presence and heartbeats of two strangers across the world.",
    concept: null,
    process: null,
    description:
      "Strangers in different places view a scene together remotely, with its visuals affected by their presence and heartbeats, allowing them to share emotions through the visuals.",
    additional: null,
  },
  {
    id: "wifi",
    imgUrl: "/static/data.png",
    tags: ["Frontend", "Data Viz"],
    year: "2020",
    firstImage: "/static/wifi/nyc.gif",
    grid: null,
    lastImage: null,
    secondImage: null,
    thirdImage: null,
    finalImage: "/static/wifi/slide.png",
    team: "Studio Elsewhere",
    role: ["Creative Technologist", "Software Engineer"],
    photoCount: null,
    title: "Wifi NYC",
    link: null,
    blurb:
      "Experiments and works in progress that I create during my free time.",
    concept: null,
    process: null,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua",
    additional: null,
  },
  {
    id: "map",
    imgUrl: "/static/map/bgmap.jpg",
    tags: ["Python", "Quantum Computing"],
    year: "2020-Present",
    firstImage: "/static/map/bg2.jpg",
    grid: ["/static/map/title.png", "/static/map/bg1.jpg"],
    lastImage: null,
    secondImage: null,
    thirdImage: null,
    finalImage: null,
    team: "Studio Elsewhere",
    role: ["Creative Technologist", "Software Engineer"],
    photoCount: null,
    title: "Community Gardens in NYC",
    link: null,
    blurb:
      "A web-based interactive data viz about internet access in each council district of New York City.",
    concept: null,
    process: null,
    description:
      "We chose to analyze and look closely at Internet Access datasets in New York City. We felt that this was a relevant topic in the current climate. The data includes information about locations with free access to wifi, including their address, wifi provider, and wifi limitations. After analyzing the data, we decided that the best way to present the information in an effect and clean way would be to create a data visualization. We hope that the visualization will demonstrate a variety of trends that will provide a deeper understanding of why certain areas have lower numbers of Internet Access. The topic of inequality in Internet access across different neighborhoods and areas is one that we hope to shine more light on.",
    additional: null,
  },
  // {
  //   id: "experiments",
  //   imgUrl: "/static/e.jpeg",
  //   tags: ["Python", "Quantum Computing"],
  //   year: "2020-Present",
  //   firstImage: null,
  //   grid: null,
  //   lastImage: null,
  //   secondImage: null,
  //   thirdImage: null,
  //   finalImage: null,
  //   team: "Studio Elsewhere",
  //   role: ["Creative Technologist", "Software Engineer"],
  //   photoCount: null,
  //   title: "Playground",
  //   link: null,
  //   blurb:
  //     "Experiments and works in progress that I create during my free time.",
  //   concept: null,
  //   process: null,
  //   description:
  //     "We chose to analyze and look closely at Internet Access datasets in New York City. We felt that this was a relevant topic in the current climate. The data includes information about locations with free access to wifi, including their address, wifi provider, and wifi limitations. After analyzing the data, we decided that the best way to present the information in an effect and clean way would be to create a data visualization. We hope that the visualization will demonstrate a variety of trends that will provide a deeper understanding of why certain areas have lower numbers of Internet Access. The topic of inequality in Internet access across different neighborhoods and areas is one that we hope to shine more light on.",
  //   additional: null,
  // },
];

export default archiveInfo;
