import { Inter } from "next/font/google";
import Footer from "../components/layout/footer";
import Layout from "../components/layout/layout";
import Navbar from "../components/layout/navbar";
import "../styles/global.css";
const montserrat = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Navbar />
        <Layout>{children}</Layout>
        <Footer />
      </body>
      {/* <body className={inter.className}>{children}</body> */}
    </html>
  );
}

// import Head from "next/head";
// import Footer from "../components/layout/footer";
// import Layout from "../components/layout/layout";
// import Navbar from "../components/layout/navbar";
// import "../styles/global.css";

// function MyApp({ Component, pageProps }) {
//   return (
//     <>
//       <Head>
//         <title>Home | Admin Panel </title>
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <Navbar />
//       <Layout>
//         <Component {...pageProps} />
//       </Layout>
//       <Footer />
//     </>
//   );
// }

// export default MyApp;
